language: python

python:
  - 3.8

services:
  postgresql
addons:
  postgresql: '9.5'

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testd;" -U postgres

script:
  - pipenv run flake8
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov